# Generated by Django 5.0.10 on 2025-01-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_phone_number_user_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_bio',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
